# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-12 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolnow', '0002_memorando'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorando',
            name='foto_usuario',
            field=models.FileField(default=b'', upload_to=b''),
        ),
    ]
