# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-13 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolnow', '0003_memorando_foto_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorando',
            name='foto_usuario',
        ),
    ]
