# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-14 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolnow', '0009_auto_20171114_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mensagem',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
