# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-15 04:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schoolnow', '0012_auto_20171115_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memorando', models.TextField(blank=True, max_length=500)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Postado em:')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='memorando',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Memorando',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
