# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-15 23:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolnow', '0016_remove_album_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagem',
            name='created_by',
        ),
    ]
