# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-17 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolnow', '0018_auto_20171115_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='memorando',
            field=models.CharField(max_length=400, verbose_name=''),
        ),
    ]
